# Generated by Django 4.2.5 on 2023-09-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekreb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_text', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ScrambledWord',
        ),
    ]
