# Generated by Django 4.2.5 on 2023-09-18 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekreb', '0002_word_delete_scrambledword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='word_text',
            new_name='word',
        ),
    ]
