# Generated by Django 4.2.5 on 2023-09-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekreb', '0003_rename_word_text_word_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=100.0)),
            ],
        ),
    ]
